import { Weapon } from '@/typescript/classes/weapon'

// prettier-ignore
export const allWeapons = [
  new Weapon( "Baseball Bat",[0],1,3,1,true,false,true,false,false,"src/assets/card-images/Season 1/baseball-bat.jpg",["s1","s2"],false,false,""),
  new Weapon( "Chainsaw",[0],5,5,2,true,true,false,false,false,"src/assets/card-images/Season 1/chainsaw.jpg",["s1","s2","rm"],false,false,""),
  new Weapon( "Crowbar",[0],1,4,1,true,true,true,true,false,"src/assets/card-images/Season 1/crowbar.jpg",["s1","rm"],false,false,""),
  new Weapon( "Evil Twins",[0,1],2,4,1,false,false,false,false,false,"src/assets/card-images/Season 1/evil-twins.jpg",["s1"],false,false,""),
  new Weapon( "Fire Axe",[0],1,4,2,true,true,true,false,false,"src/assets/card-images/Season 1/fire-axe.jpg",["s1","s2","rm"],false,false,""),
  new Weapon( "Katana",[0],2,4,1,true,false,true,false,false,"src/assets/card-images/Season 1/katana.jpg",["s1","s2"],false,false,""),
  new Weapon( "Machete",[0],1,4,2,true,false,true,false,false,"src/assets/card-images/Season 1/machete.jpg",["s1"],false,false,""),
  new Weapon( "Ma's Shotgun (Meele)",[0],1,3,2,true,false,true,false,false,"src/assets/card-images/Season 1/ma's-shotgun.jpg",["s1"],false,false,""),
  new Weapon( "Ma's Shotgun (Ranged)",[0,1],2,3,2,false,false,false,false,true,"src/assets/card-images/Season 1/ma's-shotgun.jpg",["s1"],false,false,""),
  new Weapon( "Molotov",[0,1],1000,1,1000,false,false,false,false,false,"src/assets/card-images/Season 1/molotov.jpg",["s1","s2","rm"],true,false,""),
  new Weapon( "Pan",[0],1,6,1,true,false,true,false,false,"src/assets/card-images/Season 1/pan.jpg",["s1","tcm"],false,false,""),
  new Weapon( "Pistol",[0,1],1,4,1,false,false,false,false,false,"src/assets/card-images/Season 1/pistol.jpg",["s1","s2","rm"],false,false,""),
  new Weapon( "Rifle",[1,2,3],1,3,1,false,false,false,false,false,"src/assets/card-images/Season 1/rifle.jpg",["s1","s2","rm"],false,false,""),
  new Weapon( "Sawed Off",[0,1],2,3,1,false,false,false,false,true,"src/assets/card-images/Season 1/sawed-off.jpg",["s1","s2","rm"],false,false,""),
  new Weapon( "Shotgun",[0,1],2,4,2,false,false,false,false,false,"src/assets/card-images/Season 1/shotgun.jpg",["s1","s2","rm"],false,false,""),
  new Weapon( "Sub MG",[0,1],3,5,1,false,false,false,false,false,"src/assets/card-images/Season 1/sub-mg.jpg",["s1","s2","an"],false,false,""),
  new Weapon( ".44 Magnum",[0,1],1,4,2,false,false,false,false,false,"src/assets/card-images/Toxic City Mall/44-magnum.jpg",["tcm"],false,false,""),
  new Weapon( "911 Special",[0,1,2],5,3,1,false,false,false,false,false,"src/assets/card-images/Toxic City Mall/911-special.jpg",["tcm"],false,true,""),
  new Weapon( "Assault Rifle",[1,2],3,4,1,false,false,false,false,false,"src/assets/card-images/Toxic City Mall/assault-rifle.jpg",["tcm"],false,false,""),
  new Weapon( "Betty",[0],7,4,2,true,true,false,false,false,"src/assets/card-images/Toxic City Mall/betty.jpg",["tcm"],false,true,""),
  new Weapon( "Doug's Dream",[0,1],8,4,1,false,false,false,false,false,"src/assets/card-images/Toxic City Mall/dougs-dream.jpg",["tcm"],false,true,""),
  new Weapon( "Flamethrower",[0,1],1000,1,1000,false,false,false,false,false,"src/assets/card-images/Toxic City Mall/flamethrower.jpg",["tcm"],true,false,""),
  new Weapon( "Jack & Jill",[0,1],6,3,2,false,false,false,false,true,"src/assets/card-images/Toxic City Mall/jack-and-jill.jpg",["tcm"],false,true,""),
  new Weapon( "Ned's Atomic Flashlight",[0],5,4,3,true,true,false,false,false,"src/assets/card-images/Toxic City Mall/neds-atomic-flashlight.jpg",["tcm"],false,true,""),
  new Weapon( "Pa's Gun",[0,1],1,4,3,false,false,false,false,false,"src/assets/card-images/Toxic City Mall/pa's-gun.jpg",["tcm"],false,false,""),
  new Weapon( "Sweet Sisters (Meele)",[0],6,3,2,true,false,true,false,false,"src/assets/card-images/Toxic City Mall/sweet-sisters.jpg",["tcm"],false,true,""),
  new Weapon( "Sweet Sisters (Ranged)",[0,1],4,3,2,false,false,false,false,false,"src/assets/card-images/Toxic City Mall/sweet-sisters.jpg",["tcm"],false,true,""),
  new Weapon( "Automatic Shotgun",[0,1],3,4,2,false,false,false,false,false,"src/assets/card-images/Season 2/automatic-shotgun.jpg",["s2"],false,false,""),
  new Weapon( "Claw Hammer",[0],3,5,1,true,true,true,true,false,"src/assets/card-images/Season 2/claw-hammer.jpg",["s2"],false,false,""),
  new Weapon( "Concrete Saw",[0],3,5,3,true,true,false,false,false,"src/assets/card-images/Season 2/concrete-saw.jpg",["s2"],false,false,""),
  new Weapon( "Gunblade (Meele)",[0],2,4,2,true,false,true,false,false,"src/assets/card-images/Season 2/gunblade.jpg",["s2"],false,false,""),
  new Weapon( "Gunblade (Ranged)",[0,1],1,4,2,false,false,false,false,false,"src/assets/card-images/Season 2/gunblade.jpg",["s2"],false,false,""),
  new Weapon( "Hatchet",[0],1,3,1,true,false,true,false,false,"src/assets/card-images/Season 2/hatchet.jpg",["s2"],false,false,""),
  new Weapon( "Kukri",[0],1,4,1,true,false,true,false,false,"src/assets/card-images/Season 2/kukri.jpg",["s2"],false,false,""),
  new Weapon( "Meat Cleaver",[0],1,3,2,true,false,true,false,false,"src/assets/card-images/Season 2/meat-cleaver.jpg",["s2"],false,false,""),
  new Weapon( "Nailbat",[0],2,3,2,true,false,true,false,false,"src/assets/card-images/Season 2/nailbat.jpg",["s2","rm"],false,false,""),
  new Weapon( "Night Stick",[0],1,4,1,true,false,true,false,false,"src/assets/card-images/Season 2/night-stick.jpg",["s2"],false,false,""),
  new Weapon( "Wakizachi",[0],1,3,1,true,false,true,false,false,"src/assets/card-images/Season 2/wakizachi.jpg",["s2"],false,false,"The special ability of this weapon is not implemented."),
  new Weapon( "AK-47",[1,2],2,4,2,false,false,false,false,false,"src/assets/card-images/Season 3/AK-47.jpg",["rm"],false,false,""),
  new Weapon( "Bow",[0,1],1,3,1,false,false,true,false,false,"src/assets/card-images/Angry Neighbors/Bow.jpg",["rm"],false,false,""),
  new Weapon( "Crossbow",[0,1],1,3,2,false,false,true,false,false,"src/assets/card-images/Season 3/Crossbow.jpg",["rm"],false,false,""),
  new Weapon( "Double Barrel",[0,1,2],2,3,1,false,false,false,false,true,"src/assets/card-images/Season 3/Double%20Barreled%20Shotgun.jpg",["rm"],false,false,""),
  new Weapon( "Knife",[0],1,4,1,true,false,true,false,false,"src/assets/card-images/Season 3/Knife.jpg",["rm"],false,false,"The special ability of this weapon is not implemented."),
  new Weapon( "La Guillotine",[0],4,4,2,true,true,true,false,false,"src/assets/card-images/Season 3/La%20Guillotine.jpg",["rm"],false,false,""),
  new Weapon( "Mac-10",[0,1],5,5,1,false,false,false,false,true,"src/assets/card-images/Season 3/Mac-10.jpg",["rm"],false,false,""),
  new Weapon( "MP5",[0,1],3,4,1,false,false,false,false,false,"src/assets/card-images/Season 3/MP5.jpg",["rm"],false,false,""),
  new Weapon( "Saber",[0],2,4,2,true,false,true,false,false,"src/assets/card-images/Season 3/Saber.jpg",["rm"],false,false,""),
  new Weapon( "Sword",[0],3,4,1,true,false,true,false,false,"src/assets/card-images/Season 3/Sword.jpg",["rm"],false,false,""),
  new Weapon( "Urban Mace",[0],2,3,1,true,false,true,false,false,"src/assets/card-images/Season 3/Urban%20Mace.jpg",["rm"],false,false,""),
  new Weapon( "Flaming Nailbat",[0],4,3,3,true,false,true,false,false,"src/assets/card-images/Angry Neighbors/Flaming Nailbat.jpg",["an"],false,true,""),
  new Weapon( "Nico Special",[1,2,3],3,2,2,false,true,false,false,false,"src/assets/card-images/Angry Neighbors/Nico Special.jpg",["an"],false,true,""),
  new Weapon( "SBF",[0],1,4,1,true,false,true,false,false,"src/assets/card-images/Angry Neighbors/SBF.jpg",["an"],false,false,""),
  new Weapon( "Handcannon",[0,1],3,3,1,false,false,false,false,true,"src/assets/card-images/Kickstarter & Other/Handcannon.jpg",["an"],false,false,""),
  new Weapon( "The Holy Pan",[0],3,4,2,true,false,true,false,false,"src/assets/card-images/Angry Neighbors/The Holy Pan.jpg",["an"],false,true,"The special ability of this weapon is not implemented."),
  new Weapon( "The Reaper",[0],5,5,2,true,false,true,false,false,"src/assets/card-images/Angry Neighbors/The Reaper.jpg",["an"],false,true,"The special ability of this weapon is not implemented."),
  new Weapon( "Zombicider",[0,1],0,3,1,false,false,false,false,false,"src/assets/card-images/Angry Neighbors/The Zombicider.jpg",["an"],false,true,"The special ability of this weapon is not implemented."),
  new Weapon( "Winchester",[1,2],2,4,1,false,false,false,false,false,"src/assets/card-images/Angry Neighbors/Winchester.jpg",["an"],false,false,""),
  new Weapon( "Zantetsuken",[0],4,3,2,true,false,false,false,false,"src/assets/card-images/Angry Neighbors/Zantetsuken.jpg",["an"],false,true,""),
  new Weapon( "Zomb' Knuckles",[0],1,4,1,true,false,true,false,false,"src/assets/card-images/Angry Neighbors/Zomb Knuckles.jpg",["an"],false,false,"The special ability of this weapon is not implemented."),
  new Weapon( "Daisho",[0,1],4,4,1,true,false,true,false,false,"src/assets/card-images/Kickstarter & Other/Daisho.jpg",["o"],false,false,""),
  new Weapon( "Desert Eagle",[0,1],1,4,2,false,false,false,false,false,"src/assets/card-images/Kickstarter & Other/Desert Eagle.jpg",["o"],false,false,""),
  new Weapon( "Golden AK-47",[1,2],2,4,2,false,false,false,false,false,"src/assets/card-images/Kickstarter & Other/Golden AK-47.jpg",["o"],false,false,""),
  new Weapon( "Pink M4",[0,1,2],3,4,1,false,false,false,false,false,"src/assets/card-images/Kickstarter & Other/Pink M4.jpg",["o"],false,false,""),
  new Weapon( "Ross' Bowling Ball",[1],1,2,3,false,false,true,false,false,"src/assets/card-images/Kickstarter & Other/Ross' Bowling Ball.jpg",["o"],false,false,""),
  new Weapon( "Spas 12",[0,1],3,4,2,false,false,false,false,false,"src/assets/card-images/Kickstarter & Other/SPAS 12.jpg",["o"],false,false,""),
  new Weapon( "Thompson",[0,1],5,5,1,false,false,false,false,false,"src/assets/card-images/Kickstarter & Other/Thompson.jpg",["o"],false,false,""),
  new Weapon( "Will's Comet Launcher",[2,3],1000,1,1000,false,false,false,false,false,"src/assets/card-images/Kickstarter & Other/Will's Comet Launcher.jpg",["o"],true,false,""),

  ]
