import { Weapon } from '@/components/typescript/classes/weapon'

export const weapons = [
  {
    name: 'Baseball Bat',
    range: [0],
    dices: 1,
    hit: 3,
    dmg: 1,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/baseball-bat.jpg',
  } as Weapon,
  {
    name: 'Chainsaw',
    range: [0],
    dices: 5,
    hit: 5,
    dmg: 2,
    isMeele: true,
    canOpenDoors: true,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/chainsaw.jpg',
  } as Weapon,
  {
    name: 'Crowbar',
    range: [0],
    dices: 1,
    hit: 4,
    dmg: 1,
    isMeele: true,
    canOpenDoors: true,
    isSilentAttacking: true,
    isSilentOpeningDoors: true,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/crowbar.jpg',
  } as Weapon,
  {
    name: 'Evil Twins',
    range: [0, 1],
    dices: 2,
    hit: 4,
    dmg: 1,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/evil-twins.jpg',
  } as Weapon,
  {
    name: 'Fire Axe',
    range: [0],
    dices: 1,
    hit: 4,
    dmg: 2,
    isMeele: true,
    canOpenDoors: true,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/fire-axe.jpg',
  } as Weapon,
  {
    name: 'Katana',
    range: [0],
    dices: 2,
    hit: 4,
    dmg: 1,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/katana.jpg',
  } as Weapon,
  {
    name: 'Machete',
    range: [0],
    dices: 1,
    hit: 4,
    dmg: 2,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/machete.jpg',
  } as Weapon,
  {
    name: "Ma's Shotgun (Meele)",
    range: [0],
    dices: 1,
    hit: 3,
    dmg: 2,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      "https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/ma's-shotgun.jpg",
  } as Weapon,
  {
    name: "Ma's Shotgun (Ranged)",
    range: [0, 1],
    dices: 2,
    hit: 3,
    dmg: 2,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: true,
    imagePath:
      "https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/ma's-shotgun.jpg",
  } as Weapon,
  {
    name: 'Molotov',
    range: [0, 1],
    dices: 1000,
    hit: 1,
    dmg: 1000,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/molotov.jpg',
  } as Weapon,
  {
    name: 'Pan',
    range: [0],
    dices: 1,
    hit: 6,
    dmg: 1,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/pan.jpg',
  } as Weapon,
  {
    name: 'Pistol',
    range: [0, 1],
    dices: 1,
    hit: 4,
    dmg: 1,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/pistol.jpg',
  } as Weapon,
  {
    name: 'Rifle',
    range: [1, 2, 3],
    dices: 1,
    hit: 3,
    dmg: 1,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/rifle.jpg',
  } as Weapon,
  {
    name: 'Sawed Off',
    range: [0, 1],
    dices: 2,
    hit: 3,
    dmg: 1,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: true,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/sawed-off.jpg',
  } as Weapon,
  {
    name: 'Shotgun',
    range: [0, 1],
    dices: 2,
    hit: 4,
    dmg: 2,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/shotgun.jpg',
  } as Weapon,
  {
    name: 'Sub MG',
    range: [0, 1],
    dices: 3,
    hit: 5,
    dmg: 1,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/sub-mg.jpg',
  } as Weapon,
  {
    name: '.44 Magnum',
    range: [0, 1],
    dices: 1,
    hit: 4,
    dmg: 2,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/44-magnum.jpg',
  } as Weapon,
  {
    name: '911 Special',
    range: [0, 1, 2],
    dices: 5,
    hit: 3,
    dmg: 1,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/911-special.jpg',
  } as Weapon,
  {
    name: 'Assault Rifle',
    range: [1, 2],
    dices: 3,
    hit: 4,
    dmg: 1,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/assault-rifle.jpg',
  } as Weapon,
  {
    name: 'Betty',
    range: [0],
    dices: 7,
    hit: 4,
    dmg: 2,
    isMeele: true,
    canOpenDoors: true,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/betty.jpg',
  } as Weapon,
  {
    name: "Doug's Dream",
    range: [0, 1],
    dices: 8,
    hit: 4,
    dmg: 1,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/dougs-dream.jpg',
  } as Weapon,
  {
    name: 'Flamethrower',
    range: [0, 1],
    dices: 1000,
    hit: 1,
    dmg: 1000,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/flamethrower.jpg',
  } as Weapon,
  {
    name: 'Jack & Jill',
    range: [0, 1],
    dices: 6,
    hit: 3,
    dmg: 2,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: true,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/jack-and-jill.jpg',
  } as Weapon,
  {
    name: "Ned's Atomic Flashlight",
    range: [0],
    dices: 5,
    hit: 4,
    dmg: 3,
    isMeele: true,
    canOpenDoors: true,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/neds-atomic-flashlight.jpg',
  } as Weapon,
  {
    name: "Pa's Gun",
    range: [0, 1],
    dices: 1,
    hit: 4,
    dmg: 3,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      "https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/pa's-gun.jpg",
  } as Weapon,
  {
    name: 'Sweet Sisters (Meele)',
    range: [0],
    dices: 6,
    hit: 3,
    dmg: 2,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/sweet-sisters.jpg',
  } as Weapon,
  {
    name: 'Sweet Sisters (Ranged)',
    range: [0, 1],
    dices: 4,
    hit: 3,
    dmg: 2,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/sweet-sisters.jpg',
  } as Weapon,
  {
    name: 'Automatic Shotgun',
    range: [0, 1],
    dices: 3,
    hit: 4,
    dmg: 2,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/automatic-shotgun.jpg',
  } as Weapon,
  {
    name: 'Claw Hammer',
    range: [0],
    dices: 3,
    hit: 5,
    dmg: 1,
    isMeele: true,
    canOpenDoors: true,
    isSilentAttacking: true,
    isSilentOpeningDoors: true,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/claw-hammer.jpg',
  } as Weapon,
  {
    name: 'Concrete Saw',
    range: [0],
    dices: 3,
    hit: 5,
    dmg: 3,
    isMeele: true,
    canOpenDoors: true,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/concrete-saw.jpg',
  } as Weapon,
  {
    name: 'Gunblade (Meele)',
    range: [0],
    dices: 2,
    hit: 4,
    dmg: 2,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/gunblade.jpg',
  } as Weapon,
  {
    name: 'Gunblade (Ranged)',
    range: [0, 1],
    dices: 1,
    hit: 4,
    dmg: 2,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/gunblade.jpg',
  } as Weapon,
  {
    name: 'Hatchet',
    range: [0],
    dices: 1,
    hit: 3,
    dmg: 1,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/hatchet.jpg',
  } as Weapon,
  {
    name: 'Kukri',
    range: [0],
    dices: 1,
    hit: 4,
    dmg: 1,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/kukri.jpg',
  } as Weapon,
  {
    name: 'Meat Cleaver',
    range: [0],
    dices: 1,
    hit: 3,
    dmg: 2,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/meat-cleaver.jpg',
  } as Weapon,
  {
    name: 'Nailbat',
    range: [0],
    dices: 2,
    hit: 3,
    dmg: 2,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/nailbat.jpg',
  } as Weapon,
  {
    name: 'Night Stick',
    range: [0],
    dices: 1,
    hit: 4,
    dmg: 1,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/night-stick.jpg',
  } as Weapon,
  {
    name: 'Wakizachi',
    range: [0],
    dices: 1,
    hit: 3,
    dmg: 1,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/wakizachi.jpg',
  } as Weapon,
  {
    name: 'AK-47',
    range: [1, 2],
    dices: 2,
    hit: 4,
    dmg: 2,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/AK-47.jpg',
  } as Weapon,
  {
    name: 'Bow',
    range: [0, 1],
    dices: 1,
    hit: 3,
    dmg: 1,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/Bow.jpg',
  } as Weapon,
  {
    name: 'Crossbow',
    range: [0, 1],
    dices: 1,
    hit: 3,
    dmg: 2,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/Crossbow.jpg',
  } as Weapon,
  {
    name: 'Double Barrel',
    range: [0, 1, 2],
    dices: 2,
    hit: 3,
    dmg: 1,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: true,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/Double%20Barreled%20Shotgun.jpg',
  } as Weapon,
  {
    name: 'Knife',
    range: [0],
    dices: 1,
    hit: 4,
    dmg: 1,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/Knife.jpg',
  } as Weapon,
  {
    name: 'La Guillotine',
    range: [0],
    dices: 4,
    hit: 4,
    dmg: 2,
    isMeele: true,
    canOpenDoors: true,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/La%20Guillotine.jpg',
  } as Weapon,
  {
    name: 'Mac-10',
    range: [0, 1],
    dices: 5,
    hit: 5,
    dmg: 1,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: true,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/Mac-10.jpg',
  } as Weapon,
  {
    name: 'MP5',
    range: [0, 1],
    dices: 3,
    hit: 4,
    dmg: 1,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/MP5.jpg',
  } as Weapon,
  {
    name: 'Saber',
    range: [0],
    dices: 2,
    hit: 4,
    dmg: 2,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/Saber.jpg',
  } as Weapon,
  {
    name: 'Sword',
    range: [0],
    dices: 3,
    hit: 4,
    dmg: 1,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/Sword.jpg',
  } as Weapon,
  {
    name: 'Urban Mace',
    range: [0],
    dices: 2,
    hit: 3,
    dmg: 1,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/Urban%20Mace.jpg',
  } as Weapon,
  {
    name: 'Flaming Nailbat',
    range: [0],
    dices: 4,
    hit: 3,
    dmg: 3,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/Flaming%20Nailbat.jpg',
  } as Weapon,
  {
    name: 'Nico Special',
    range: [1, 2, 3],
    dices: 3,
    hit: 2,
    dmg: 2,
    isMeele: false,
    canOpenDoors: true,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/Nico%20Special.jpg',
  } as Weapon,
  {
    name: 'SBF',
    range: [0],
    dices: 1,
    hit: 4,
    dmg: 1,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/SBF.jpg',
  } as Weapon,
  {
    name: 'Handcannon',
    range: [0, 1],
    dices: 3,
    hit: 3,
    dmg: 1,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: true,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/Handcannon.jpg',
  } as Weapon,
  {
    name: 'The Holy Pan',
    range: [0],
    dices: 3,
    hit: 4,
    dmg: 2,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/The%20Holy%20Pan.jpg',
  } as Weapon,
  {
    name: 'The Reaper',
    range: [0],
    dices: 5,
    hit: 5,
    dmg: 2,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/The%20Reaper.jpg',
  } as Weapon,
  {
    name: 'Zombicider',
    range: [0, 1],
    dices: 0,
    hit: 3,
    dmg: 1,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/The%20Zombicider.jpg',
  } as Weapon,
  {
    name: 'Winchester',
    range: [1, 2],
    dices: 2,
    hit: 4,
    dmg: 1,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/Winchester.jpg',
  } as Weapon,
  {
    name: 'Zantetsuken',
    range: [0],
    dices: 4,
    hit: 3,
    dmg: 2,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/Zantetsuken.jpg',
  } as Weapon,
  {
    name: "Zomb' Knuckles",
    range: [0],
    dices: 1,
    hit: 4,
    dmg: 1,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/Zomb%20Knuckles.jpg',
  } as Weapon,
  {
    name: 'Daisho',
    range: [0, 1],
    dices: 4,
    hit: 4,
    dmg: 1,
    isMeele: true,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/other/Daisho.jpg',
  } as Weapon,
  {
    name: 'Desert Eagle',
    range: [0, 1],
    dices: 1,
    hit: 4,
    dmg: 2,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/other/Desert%20Eagle.jpg',
  } as Weapon,
  {
    name: 'Golden AK-47',
    range: [1, 2],
    dices: 2,
    hit: 4,
    dmg: 2,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/other/Golden%20AK-47.jpg',
  } as Weapon,
  {
    name: 'Pink M4',
    range: [0, 1, 2],
    dices: 3,
    hit: 4,
    dmg: 1,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/other/Pink%20M4.jpg',
  } as Weapon,
  {
    name: "Ross' Bowling Ball",
    range: [1],
    dices: 1,
    hit: 2,
    dmg: 3,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: true,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      "https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/other/Ross'%20Bowling%20Ball.jpg",
  } as Weapon,
  {
    name: 'Spas 12',
    range: [0, 1],
    dices: 3,
    hit: 4,
    dmg: 2,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/other/SPAS%2012.jpg',
  } as Weapon,
  {
    name: 'Thompson',
    range: [0, 1],
    dices: 5,
    hit: 5,
    dmg: 1,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/other/Thompson.jpg',
  } as Weapon,
  {
    name: "Will's Comet Launcher",
    range: [2, 3],
    dices: 1000,
    hit: 1,
    dmg: 1000,
    isMeele: false,
    canOpenDoors: false,
    isSilentAttacking: false,
    isSilentOpeningDoors: false,
    reload: false,
    imagePath:
      "https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/other/Will's%20Comet%20Launcher.jpg",
  } as Weapon,
]
