import { Weapon } from '@/components/typescript/classes/weapon'

export const weapons = [
  new Weapon(
    'Baseball Bat',
    [0],
    1,
    3,
    1,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/baseball-bat.jpg',
  ),
  new Weapon(
    'Chainsaw',
    [0],
    5,
    5,
    2,
    true,
    true,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/chainsaw.jpg',
  ),
  new Weapon(
    'Crowbar',
    [0],
    1,
    4,
    1,
    true,
    true,
    true,
    true,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/crowbar.jpg',
  ),
  new Weapon(
    'Evil Twins',
    [0, 1],
    2,
    4,
    1,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/evil-twins.jpg',
  ),
  new Weapon(
    'Fire Axe',
    [0],
    1,
    4,
    2,
    true,
    true,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/fire-axe.jpg',
  ),
  new Weapon(
    'Katana',
    [0],
    2,
    4,
    1,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/katana.jpg',
  ),
  new Weapon(
    'Machete',
    [0],
    1,
    4,
    2,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/machete.jpg',
  ),
  new Weapon(
    "Ma's Shotgun (Meele)",
    [0],
    1,
    3,
    2,
    true,
    false,
    true,
    false,
    false,
    "https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/ma's-shotgun.jpg",
  ),
  new Weapon(
    "Ma's Shotgun (Ranged)",
    [0, 1],
    2,
    3,
    2,
    false,
    false,
    false,
    false,
    true,
    "https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/ma's-shotgun.jpg",
  ),
  new Weapon(
    'Molotov',
    [0, 1],
    1000,
    1,
    1000,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/molotov.jpg',
  ),
  new Weapon(
    'Pan',
    [0],
    1,
    6,
    1,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/pan.jpg',
  ),
  new Weapon(
    'Pistol',
    [0, 1],
    1,
    4,
    1,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/pistol.jpg',
  ),
  new Weapon(
    'Rifle',
    [1, 2, 3],
    1,
    3,
    1,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/rifle.jpg',
  ),
  new Weapon(
    'Sawed Off',
    [0, 1],
    2,
    3,
    1,
    false,
    false,
    false,
    false,
    true,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/sawed-off.jpg',
  ),
  new Weapon(
    'Shotgun',
    [0, 1],
    2,
    4,
    2,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/shotgun.jpg',
  ),
  new Weapon(
    'Sub MG',
    [0, 1],
    3,
    5,
    1,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/1/sub-mg.jpg',
  ),
  new Weapon(
    '.44 Magnum',
    [0, 1],
    1,
    4,
    2,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/44-magnum.jpg',
  ),
  new Weapon(
    '911 Special',
    [0, 1, 2],
    5,
    3,
    1,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/911-special.jpg',
  ),
  new Weapon(
    'Assault Rifle',
    [1, 2],
    3,
    4,
    1,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/assault-rifle.jpg',
  ),
  new Weapon(
    'Betty',
    [0],
    7,
    4,
    2,
    true,
    true,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/betty.jpg',
  ),
  new Weapon(
    "Doug's Dream",
    [0, 1],
    8,
    4,
    1,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/dougs-dream.jpg',
  ),
  new Weapon(
    'Flamethrower',
    [0, 1],
    1000,
    1,
    1000,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/flamethrower.jpg',
  ),
  new Weapon(
    'Jack & Jill',
    [0, 1],
    6,
    3,
    2,
    false,
    false,
    false,
    false,
    true,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/jack-and-jill.jpg',
  ),
  new Weapon(
    "Ned's Atomic Flashlight",
    [0],
    5,
    4,
    3,
    true,
    true,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/neds-atomic-flashlight.jpg',
  ),
  new Weapon(
    "Pa's Gun",
    [0, 1],
    1,
    4,
    3,
    false,
    false,
    false,
    false,
    false,
    "https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/pa's-gun.jpg",
  ),
  new Weapon(
    'Sweet Sisters (Meele)',
    [0],
    6,
    3,
    2,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/sweet-sisters.jpg',
  ),
  new Weapon(
    'Sweet Sisters (Ranged)',
    [0, 1],
    4,
    3,
    2,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/3/sweet-sisters.jpg',
  ),
  new Weapon(
    'Automatic Shotgun',
    [0, 1],
    3,
    4,
    2,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/automatic-shotgun.jpg',
  ),
  new Weapon(
    'Claw Hammer',
    [0],
    3,
    5,
    1,
    true,
    true,
    true,
    true,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/claw-hammer.jpg',
  ),
  new Weapon(
    'Concrete Saw',
    [0],
    3,
    5,
    3,
    true,
    true,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/concrete-saw.jpg',
  ),
  new Weapon(
    'Gunblade (Meele)',
    [0],
    2,
    4,
    2,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/gunblade.jpg',
  ),
  new Weapon(
    'Gunblade (Ranged)',
    [0, 1],
    1,
    4,
    2,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/gunblade.jpg',
  ),
  new Weapon(
    'Hatchet',
    [0],
    1,
    3,
    1,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/hatchet.jpg',
  ),
  new Weapon(
    'Kukri',
    [0],
    1,
    4,
    1,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/kukri.jpg',
  ),
  new Weapon(
    'Meat Cleaver',
    [0],
    1,
    3,
    2,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/meat-cleaver.jpg',
  ),
  new Weapon(
    'Nailbat',
    [0],
    2,
    3,
    2,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/nailbat.jpg',
  ),
  new Weapon(
    'Night Stick',
    [0],
    1,
    4,
    1,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/night-stick.jpg',
  ),
  new Weapon(
    'Wakizachi',
    [0],
    1,
    3,
    1,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/2/wakizachi.jpg',
  ),
  new Weapon(
    'AK-47',
    [1, 2],
    2,
    4,
    2,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/AK-47.jpg',
  ),
  new Weapon(
    'Bow',
    [0, 1],
    1,
    3,
    1,
    false,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/Bow.jpg',
  ),
  new Weapon(
    'Crossbow',
    [0, 1],
    1,
    3,
    2,
    false,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/Crossbow.jpg',
  ),
  new Weapon(
    'Double Barrel',
    [0, 1, 2],
    2,
    3,
    1,
    false,
    false,
    false,
    false,
    true,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/Double%20Barreled%20Shotgun.jpg',
  ),
  new Weapon(
    'Knife',
    [0],
    1,
    4,
    1,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/Knife.jpg',
  ),
  new Weapon(
    'La Guillotine',
    [0],
    4,
    4,
    2,
    true,
    true,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/La%20Guillotine.jpg',
  ),
  new Weapon(
    'Mac-10',
    [0, 1],
    5,
    5,
    1,
    false,
    false,
    false,
    false,
    true,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/Mac-10.jpg',
  ),
  new Weapon(
    'MP5',
    [0, 1],
    3,
    4,
    1,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/MP5.jpg',
  ),
  new Weapon(
    'Saber',
    [0],
    2,
    4,
    2,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/Saber.jpg',
  ),
  new Weapon(
    'Sword',
    [0],
    3,
    4,
    1,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/Sword.jpg',
  ),
  new Weapon(
    'Urban Mace',
    [0],
    2,
    3,
    1,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/4/Urban%20Mace.jpg',
  ),
  new Weapon(
    'Flaming Nailbat',
    [0],
    4,
    3,
    3,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/Flaming%20Nailbat.jpg',
  ),
  new Weapon(
    'Nico Special',
    [1, 2, 3],
    3,
    2,
    2,
    false,
    true,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/Nico%20Special.jpg',
  ),
  new Weapon(
    'SBF',
    [0],
    1,
    4,
    1,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/SBF.jpg',
  ),
  new Weapon(
    'Handcannon',
    [0, 1],
    3,
    3,
    1,
    false,
    false,
    false,
    false,
    true,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/Handcannon.jpg',
  ),
  new Weapon(
    'The Holy Pan',
    [0],
    3,
    4,
    2,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/The%20Holy%20Pan.jpg',
  ),
  new Weapon(
    'The Reaper',
    [0],
    5,
    5,
    2,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/The%20Reaper.jpg',
  ),
  new Weapon(
    'Zombicider',
    [0, 1],
    0,
    3,
    1,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/The%20Zombicider.jpg',
  ),
  new Weapon(
    'Winchester',
    [1, 2],
    2,
    4,
    1,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/Winchester.jpg',
  ),
  new Weapon(
    'Zantetsuken',
    [0],
    4,
    3,
    2,
    true,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/Zantetsuken.jpg',
  ),
  new Weapon(
    "Zomb' Knuckles",
    [0],
    1,
    4,
    1,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/5/Zomb%20Knuckles.jpg',
  ),
  new Weapon(
    'Daisho',
    [0, 1],
    4,
    4,
    1,
    true,
    false,
    true,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/other/Daisho.jpg',
  ),
  new Weapon(
    'Desert Eagle',
    [0, 1],
    1,
    4,
    2,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/other/Desert%20Eagle.jpg',
  ),
  new Weapon(
    'Golden AK-47',
    [1, 2],
    2,
    4,
    2,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/other/Golden%20AK-47.jpg',
  ),
  new Weapon(
    'Pink M4',
    [0, 1, 2],
    3,
    4,
    1,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/other/Pink%20M4.jpg',
  ),
  new Weapon(
    "Ross' Bowling Ball",
    [1],
    1,
    2,
    3,
    false,
    false,
    true,
    false,
    false,
    "https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/other/Ross'%20Bowling%20Ball.jpg",
  ),
  new Weapon(
    'Spas 12',
    [0, 1],
    3,
    4,
    2,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/other/SPAS%2012.jpg',
  ),
  new Weapon(
    'Thompson',
    [0, 1],
    5,
    5,
    1,
    false,
    false,
    false,
    false,
    false,
    'https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/other/Thompson.jpg',
  ),
  new Weapon(
    "Will's Comet Launcher",
    [2, 3],
    1000,
    1,
    1000,
    false,
    false,
    false,
    false,
    false,
    "https://patrickgalbraith.github.io/zombicide-card-database/img/cards/equipment/other/Will's%20Comet%20Launcher.jpg",
  ),
]
